spring:
  redis:
    host: localhost
    port: 6379
    password: 
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: aiplatform-auth
          uri: lb://aiplatform-auth
          predicates:
            - Path=/dev-api/auth/**
          filters:
            # 验证码处理
            - CacheRequestFilter
            - ValidateCodeFilter
            - StripPrefix=2
        # 代码生成
        - id: aiplatform-gen
          uri: lb://aiplatform-gen
          predicates:
            - Path=/dev-api/code/**
          filters:
            - StripPrefix=2
        # 定时任务
        - id: aiplatform-job
          uri: lb://aiplatform-job
          predicates:
            - Path=/dev-api/schedule/**
          filters:
            - StripPrefix=2
        # 系统模块
        - id: aiplatform-system
          uri: lb://aiplatform-system
          predicates:
            - Path=/dev-api/system/**
          filters:
            - StripPrefix=2
        # 数据集服务（带dev-api前缀）
        - id: aiplatform-dataset-dev
          uri: lb://aiplatform-dataset
          predicates:
            - Path=/dev-api/dataset/**
          filters:
            - StripPrefix=2

# 安全配置
security:
  # 验证码
  captcha:
    enabled: true
    type: math
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
      - /system/notice

  # 不校验白名单
  ignore:
    whites:
      - /auth/logout
      - /auth/login
      - /auth/register
      - /*/v2/api-docs
      - /*/v3/api-docs
      - /csrf
      - /api/v1/**

# springdoc配置
springdoc:
  webjars:
    # 访问前缀
    prefix: 